default_language_version:
  python: python3.8.18

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    - id: autopep8
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      args: ["--ignore=E501,W503,W504"]
  - repo: https://github.com/pre-commit/pre-commit
    rev: v1.7.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.0.1
    hooks:
      - id: reorder-python-imports
        language_version: '3.8'
  - repo: meta
    hooks:
      - id: check-useless-excludes
